/** Bundle the API into a single Vercel-compatible serverless function. */
import { build } from "esbuild";
import { existsSync, mkdirSync } from "node:fs";
import { dirname, resolve } from "node:path";

/**
 * The source imports sibling modules with a `.js` extension, which is what
 * TypeScript's ESM output expects, while the files on disk are `.ts`. Vite and
 * vitest resolve that themselves; a bare esbuild run does not, so map relative
 * `.js` specifiers onto the `.ts` file that actually exists.
 */
const resolveTsExtensions = {
  name: "resolve-ts-extensions",
  setup(pluginBuild) {
    pluginBuild.onResolve({ filter: /^\.{1,2}\/.*\.js$/ }, (args) => {
      const base = resolve(dirname(args.importer), args.path);
      const candidate = base.replace(/\.js$/, ".ts");
      if (existsSync(candidate)) return { path: candidate };
      if (existsSync(base)) return { path: base };
      return null;
    });
  },
};

mkdirSync("api", { recursive: true });
await build({
  entryPoints: ["packages/api/src/vercel.ts"],
  bundle: true,
  platform: "node",
  target: "node22",
  format: "esm",
  outfile: "api/index.js",
  plugins: [resolveTsExtensions],
  banner: { js: "// Generated by scripts/build-api.mjs. Do not edit." },
  logLevel: "info",
});
